video:
  size:
    width: 2560
    height: 1440
  rtsp_urls:
    - "rtsp://admin:Daxhuz-kitnor-cekvi5@192.168.3.49/Preview_01_main"
    - "rtsp://admin:Daxhuz-kitnor-cekvi5@192.168.3.47/Preview_01_main"
    - "rtsp://admin:Daxhuz-kitnor-cekvi5@192.168.3.52/Preview_01_main"
  active_url: 2

model:
  path: "models/yolov8m-pose.pt"

#47

points_2d:
  - [1539, 653] #
  - [1588, 590] #
  - [1846, 691] 
  - [1845, 689] 
  - [1578, 421] 
points_3d:
  - [0, 0, 0] #
  - [-60, 0, 0] #
  - [0, 118, 0] 
  - [-60, 118, 0] 
  - [-60, 0, 71] 


#49

points_2d:
  - [1879, 1186] #
  - [1657, 1165] #
  - [1901, 728] 
  - [1707, 716] 
  - [1686, 927] 
points_3d:
  - [0, 0, 0] #
  - [-60, 0, 0] #
  - [0, 118, 71] 
  - [-60, 118, 71] 
  - [-60, 0, 71] 


#51

points_2d:
  - [191, 933] #
  - [119, 918] #
  - [349, 783] 
  - [271, 778] 
  - [61, 761] 
points_3d:
  - [0, 0, 0] #
  - [-60, 0, 0] #
  - [0, 118, 0] 
  - [-60, 118, 0] 
  - [-60, 0, 71] 